[font]
size = 14.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Italic"

[window]
opacity = 0.94
padding = { x = 8, y = 8 }
dynamic_padding = false


[scrolling]
history = 10000
multiplier = 3
