#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap latam &
pgrep -x xautolock >/dev/null || xautolock -time 30 -locker "betterlockscreen -l dim" &

bspc monitor HDMI-A-0 -d I II III VI 
bspc monitor HDMI-A-1 -d IV V VII 

bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false

# Reglas de ventanas
bspc rule -a firefox desktop='I' follow=on
bspc rule -a Chromium desktop='IV' follow=off
bspc rule -a discord desktop='III' follow=off
bspc rule -a steam desktop='II' follow=off

bspc config normal_border_color "#333333"
bspc config active_border_color "#555555"
bspc config focused_border_color "#888888"

xrandr --output HDMI-A-0 --mode 1680x1050 --pos 0x0 --primary --output HDMI-A-1 --mode 1600x900 --pos 1680x150

sleep 1
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &
killall -q polybar
~/.config/polybar/launch.sh --shades &

feh --bg-fill ~/Pictures/wallpapers/bg1.jpg &

sleep 1
pgrep -x firefox >/dev/null || firefox &
pgrep -x chromium >/dev/null || chromium &

pgrep -u "$USER" -x greenclip >/dev/null || greenclip daemon &
# Teclado numérico siempre activo
numlockx on &

# Enter del numpad como Enter normal
xmodmap -e "keycode 104 = Return" &
